// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesManagement.CashFlow.Infrastructure.Persistence.Contexts;

#nullable disable

namespace SalesManagement.CashFlow.Infrastructure.Migrations
{
    [DbContext(typeof(CashFlowContext))]
    [Migration("20230114202021_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("CashFlow")
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalesManagement.CashFlow.Domain.Entities.LancamentoBancario", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Categoria");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("CriadoEm")
                        .HasDefaultValueSql("GetDate()");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Descricao");

                    b.Property<int>("TipoLancamentoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Valor");

                    b.HasKey("Id");

                    b.HasIndex("TipoLancamentoId")
                        .HasDatabaseName("IX_LancamentoBancario_TipoLancamentoId");

                    b.ToTable("LancamentoBancario", "CashFlow");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Agua",
                            CriadoEm = new DateTime(2023, 1, 14, 17, 20, 21, 478, DateTimeKind.Local).AddTicks(9699),
                            Descricao = "Conta da Sabesp",
                            TipoLancamentoId = 1,
                            Valor = 100.0m
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Folha de Pagamento",
                            CriadoEm = new DateTime(2023, 1, 14, 17, 20, 21, 478, DateTimeKind.Local).AddTicks(9710),
                            Descricao = "Despesa com funcionários",
                            TipoLancamentoId = 1,
                            Valor = 100000.0m
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Recebivéis",
                            CriadoEm = new DateTime(2023, 1, 14, 17, 20, 21, 478, DateTimeKind.Local).AddTicks(9717),
                            Descricao = "Venda para client X",
                            TipoLancamentoId = 2,
                            Valor = 200000.0m
                        },
                        new
                        {
                            Id = 4,
                            Categoria = "Recebivéis",
                            CriadoEm = new DateTime(2023, 1, 14, 17, 20, 21, 478, DateTimeKind.Local).AddTicks(9723),
                            Descricao = "Venda para client Y",
                            TipoLancamentoId = 2,
                            Valor = 100000.0m
                        });
                });

            modelBuilder.Entity("SalesManagement.CashFlow.Domain.Entities.TipoLancamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoLancamento", "CashFlow");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CriadoEm = new DateTime(2023, 1, 14, 17, 20, 21, 478, DateTimeKind.Local).AddTicks(9638),
                            Nome = "Debit"
                        },
                        new
                        {
                            Id = 2,
                            CriadoEm = new DateTime(2023, 1, 14, 17, 20, 21, 478, DateTimeKind.Local).AddTicks(9688),
                            Nome = "Credit"
                        });
                });

            modelBuilder.Entity("SalesManagement.CashFlow.Domain.Entities.LancamentoBancario", b =>
                {
                    b.HasOne("SalesManagement.CashFlow.Domain.Entities.TipoLancamento", "TipoLancamento")
                        .WithOne("LancamentoBancario")
                        .HasForeignKey("SalesManagement.CashFlow.Domain.Entities.LancamentoBancario", "TipoLancamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoLancamento");
                });

            modelBuilder.Entity("SalesManagement.CashFlow.Domain.Entities.TipoLancamento", b =>
                {
                    b.Navigation("LancamentoBancario");
                });
#pragma warning restore 612, 618
        }
    }
}
